In [1]:
import pandas as pd

In [2]:
import numpy as np

In [ ]:
#Create 3 differents Series, each of length 100

In [3]:
#The first a random number from 1 to 4
s1 = pd.Series(np.random.randint(1, high=5, size=100, dtype='l'))

In [4]:
#The second a random number from 1 to 3
s2 = pd.Series(np.random.randint(1, high=4, size=100, dtype='l'))

In [5]:
#The third a random number from 10,000 to 30,000
s3 = pd.Series(np.random.randint(10000, high=30001, size=100,
dtype='l'))

In [7]:
print(s1, s2, s3)

0     4
1     1
2     2
3     3
4     2
     ..
95    3
96    1
97    1
98    1
99    2
Length: 100, dtype: int32 0     2
1     2
2     3
3     1
4     1
     ..
95    3
96    3
97    2
98    1
99    1
Length: 100, dtype: int32 0     22396
1     12742
2     25112
3     21876
4     21371
      ...
95    13580
96    17564
97    22023
98    24938
99    29203
Length: 100, dtype: int32

In [8]:
housemkt = pd.concat([s1, s2, s3], axis=1)
housemkt.head()

   0  1      2
0  4  2  22396
1  1  2  12742
2  2  3  25112
3  3  1  21876
4  2  1  21371

In [9]:
housemkt.rename(columns = {0: 'bedrs', 1: 'bathrs', 2:
'price_sqr_meter'}, inplace=True)
housemkt.head()

   bedrs  bathrs  price_sqr_meter
0      4       2            22396
1      1       2            12742
2      2       3            25112
3      3       1            21876
4      2       1            21371

In [10]:
# join concat the values
bigcolumn = pd.concat([s1, s2, s3], axis=0)

In [11]:
# it is still a Series, so we need to transform it to a DataFrame
bigcolumn = bigcolumn.to_frame()

In [12]:
print(type(bigcolumn))

<class 'pandas.core.frame.DataFrame'>

In [13]:
# no the index are kept but the length of the DataFrame is 300
len(bigcolumn)

300

In [15]:
#Reindex the DataFrame so it goes from 0 to 299
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn

         0
0        4
1        1
2        2
3        3
4        2
..     ...
295  13580
296  17564
297  22023
298  24938
299  29203

[300 rows x 1 columns]